name: Release

on:
  workflow_run:
    workflows: ["Build"]
    branches: [ master ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.402'
    - name: Install dependencies
      run: dotnet restore src/Anvyl.JsonLocalizer
    - name: Build
      run: dotnet build src/Anvyl.JsonLocalizer --configuration Release --no-restore
    - name: Publish to NuGet
      uses: Rebel028/publish-nuget@303a8b8c070b46bc3a1f32a97c0930fbc9f17027
      with:
        PROJECT_FILE_PATH: src/Anvyl.JsonLocalizer/Anvyl.JsonLocalizer.csproj
        TAG_FORMAT: 'v*-beta'
        NUGET_SOURCE: https://nuget.pkg.github.com/amoraitis  
        NUGET_KEY: ${{secrets.PACKAGES_API_KEY}}
